spring:
  application:
    name: user-ms

  datasource:
    url: jdbc:mysql://localhost:3308/user_db
    username: root
    password: Netec123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081